"""Editable Recipe-MCTS configuration for the TSP task."""

MCTS_RECIPE_CONFIG = {
    "log_dir": "logs/mcts_recipe_tsp",
    "checkpoint": None,
    "mode": "reflection",
    "operators": ("e1", "e2", "m1", "m2"),
    "mcts": {
        "pop_size": 5,
        "selection_num": 2,
        "max_depth": 50,
        "max_sample_count": 10000,
        "initialization_mode": "refineevo",
        "initial_sample_nums_max": None,
        "init_pop_size": 30,
        "num_samplers": 5,
        "num_evaluators": 5,
        "exploration_constant": 0.2,
        "depth_balance_weight": 0.4,
        "node_batch_size": 10,
        "seed": None,
        "elite_pool_size": 20,
        "debug": False,
    },
    "llm": {
        "host": "api.apilio.ai",
        "api_key": "",
        "api_key_env": ["LLM4AD_API_KEY"],
        "model": "gpt-4o-mini",
        "timeout": 60,
    },
    "embedding": {
        "base_url": "https://api.apilio.ai/v1",
        "api_key": "",
        "api_key_env": ["LLM4AD_EMBEDDING_API_KEY", "OPENAI_API_KEY8", "LLM4AD_API_KEY"],
        "model": "text-embedding-v4",
        "encoding_format": "float",
        "top_k": 3,
    },
    "evaluation": {
        "mode": "refineevo",
        "timeout_seconds": 300,
        "n_instance": 50,
        "problem_size": 100,
        "dataset_path": '/public/home/liuyang/dataset/tsp/tsp_instances_train_100.pkl',
        "seed": 2024,
    },
    "test": {
        "enabled": False,
        "task": "tsp",
        "data_paths": [],
        "output": "tsp_test_results.csv",
        "max_nodes": 0,
        "instance_timeout": 1800,
    },
}
