from __future__ import annotations

from typing import List, Dict

from ...base import *


class EoHPrompt:
    _COMPARISON_INSTRUCTION = (
        'Compare the provided algorithms, identify their important design differences, '
        'and determine which differences are associated with better or worse performance.'
    )
    _COMPARISON_TASKS = {
        'reference': 'Compare the provided reference algorithms and identify useful design differences.',
        'parent_child': 'Compare parent and child algorithms and identify changes associated with performance differences.',
        'elite_worst': 'Compare the population elite and worst algorithms and identify the structural reasons for their quality gap.',
        'elite_average': 'Compare the population elite with an average-quality algorithm.',
        'worst_average': 'Compare the population worst algorithm with an average-quality algorithm.',
        'children_same_parents': 'Compare multiple children whose complete parent sets are identical.',
        'children_shared_parent': 'Compare multiple children that share at least one parent.',
        'success_failure': 'Compare successful and failed modifications and identify patterns associated with improvement.',
        'operator': 'Compare algorithms generated by different evolutionary operators.',
        'instance': 'Compare algorithm behavior across different instances and instance characteristics.',
        'behavior': 'Compare behavioral features such as selections, route structure, or constraint handling.',
    }
    _ATTRIBUTION_TASKS = {
        'good': 'Attribute good performance or performance improvements to concrete algorithm design decisions supported by the input.',
        'bad': 'Attribute poor performance or performance degradation to concrete algorithm design decisions supported by the input.',
        'both': 'Attribute both beneficial and harmful outcomes to concrete algorithm design decisions supported by the input.',
        'difference': 'Attribute observed performance differences to specific differences between the algorithms or conditions.',
        'same': 'Explain why the algorithms obtain similar performance despite their design differences.',
    }
    _SUMMARY_TASKS = {
        'guidance': 'Summarize the provided information into concrete guidance for the next algorithm generation.',
        'experience': 'Summarize the provided cases into transferable heuristic experience.',
        'conditions': 'Extract design principles and state the conditions under which each principle applies.',
    }

    @classmethod
    def _processing_block(cls, behavior_type='comparison', behavior_task=None):
        tables = {'comparison': cls._COMPARISON_TASKS, 'attribution': cls._ATTRIBUTION_TASKS,
                  'summarization': cls._SUMMARY_TASKS}
        if behavior_type not in tables:
            raise ValueError(f'Unknown behavior_type {behavior_type!r}.')
        if behavior_type == 'comparison':
            return f'Comparison: {cls._COMPARISON_INSTRUCTION}'
        table = tables[behavior_type]
        task = behavior_task or next(iter(table))
        if task not in table:
            raise ValueError(f'Unknown {behavior_type} task {task!r}; choose from {", ".join(table)}.')
        labels = {
            'comparison': 'Comparison',
            'attribution': 'Attribution',
            'summarization': 'Summary',
        }
        return f'{labels[behavior_type]}: {table[task]}'
    @staticmethod
    def _reflection_output_block(output_fields=None, insight_flag=None,
                                 cause_flag=None, suggestion_flag=None,
                                 experience_flag=None) -> str:
        # Reflection output is intentionally fixed for the current study.
        # The LLM must return only one actionable guide for the next evolution.
        return ('Based on the above thoughts, output one specific improvement suggestion inside {}. '
                'Do not output code, or extra explanations.')

    @staticmethod
    def _reflection_input_block(parent_info_flag, best_worst_flag,
                                fitness_flag, avg_fitness_flag):
        blocks = ['selected candidate code']
        if parent_info_flag:
            blocks.append('parent candidates when available')
        if best_worst_flag:
            blocks.append('best and worst population candidates')
        if fitness_flag >= 1:
            blocks.append('candidate thought')
        if fitness_flag >= 2:
            blocks.append('candidate score')
        if avg_fitness_flag:
            blocks.append('population mean score')
        return '\n'.join(f'- {b}' for b in blocks)

    @staticmethod
    def _build_parent_child_input(children, parent_groups, algorithm_block):
        """Build parent-child evolution paths, omitting children without parents."""
        selected = [(child, group) for child, group in zip(children, parent_groups)
                    if group]
        selected_children = [child for child, _ in selected]
        selected_parent_groups = [group for _, group in selected]
        sections = [
            '===== parents vs. children =====\n'
            'Here are the reference algorithm sets from the previous algorithm design '
            'and the new algorithms generated from them to complete the above task.'
        ]
        for i, (child, group) in enumerate(
                zip(selected_children, selected_parent_groups), 1):
            path_label = ('## Evolution path ##' if len(selected_children) == 1
                          else f'## Evolution path {i} ##')
            section = [path_label]
            for j, parent in enumerate(group, 1):
                parent_label = ('# Reference Algorithm #' if len(group) == 1
                                else f'# Reference Algorithm {j} #')
                section.extend((parent_label,
                                algorithm_block(parent, include_guidance=False)))
            section.extend(('# Generated Algorithm #',
                            algorithm_block(child, include_guidance=True)))
            sections.append('\n'.join(section))
        return sections

    @staticmethod
    def _build_population_pair_input(title, description, first_label, first,
                                     second_label, second, algorithm_block):
        return [
            f'===== {title} =====\n{description}\n'
            f'## {first_label} ##\n{algorithm_block(first, include_guidance=False)}\n'
            f'## {second_label} ##\n{algorithm_block(second, include_guidance=False)}'
        ]

    @classmethod
    def _build_elite_worst_input(cls, population_items, algorithm_block,
                                 score_key):
        ranked = sorted(population_items, key=score_key)
        return cls._build_population_pair_input(
            'elite vs. worst',
            'Here are the elite and worst algorithms in the current population.',
            'Elite Algorithm', ranked[0], 'Worst Algorithm', ranked[-1],
            algorithm_block)

    @staticmethod
    def _population_representatives(population_items, score_key):
        ranked = sorted(population_items, key=score_key)
        mean_score = sum(score_key(item) for item in ranked) / len(ranked)
        average = min(ranked, key=lambda item: abs(score_key(item) - mean_score))
        return ranked[0], ranked[-1], average

    @classmethod
    def _build_elite_average_input(cls, population_items, algorithm_block,
                                   score_key):
        elite, _, average = cls._population_representatives(
            population_items, score_key)
        return cls._build_population_pair_input(
            'elite vs. population-average individual',
            'The population-average individual is the real individual whose score is closest to the population mean.',
            'Elite Algorithm', elite, 'Population-average Algorithm', average,
            algorithm_block)

    @classmethod
    def _build_worst_average_input(cls, population_items, algorithm_block,
                                   score_key):
        _, worst, average = cls._population_representatives(
            population_items, score_key)
        return cls._build_population_pair_input(
            'worst vs. population-average individual',
            'The population-average individual is the real individual whose score is closest to the population mean.',
            'Worst Algorithm', worst, 'Population-average Algorithm', average,
            algorithm_block)

    @staticmethod
    def _parent_identity(parent):
        return getattr(parent, '_eoh_lineage_id', None) or id(parent)

    @classmethod
    def _build_sibling_input(cls, children, parent_groups, algorithm_block,
                             allow_identical=True, allow_shared=True):
        """Classify selected children by their parent relationship.

        Returns ``(sections, task)``.  If the selected children do not form a
        valid sibling comparison, both values are ``None`` so the caller can
        use the basic reference prompt.
        """
        if len(children) < 2 or any(not group for group in parent_groups):
            return None, None
        parent_sets = [{cls._parent_identity(parent) for parent in group}
                       for group in parent_groups]
        identical = all(group == parent_sets[0] for group in parent_sets[1:])
        shared_parent_ids = set.intersection(*parent_sets)
        shared = bool(shared_parent_ids)
        if identical and allow_identical:
            title = 'children with identical parents'
            description = 'These children have exactly the same complete parent set.'
            task = 'children_same_parents'
        elif shared and allow_shared:
            title = 'children with a shared parent'
            description = 'These children share at least one parent.'
            task = 'children_shared_parent'
        else:
            return None, None
        sections = [f'===== {title} =====\n{description}']
        if identical:
            for index, parent in enumerate(parent_groups[0], 1):
                sections.append(
                    f'## Parent Algorithm {index} ##\n'
                    f'{algorithm_block(parent, include_guidance=False)}')
            for index, child in enumerate(children, 1):
                sections.append(
                    f'## Child Algorithm {index} ##\n'
                    f'{algorithm_block(child, include_guidance=True)}')
        else:
            shared_parents = []
            seen = set()
            for parent in parent_groups[0]:
                parent_id = cls._parent_identity(parent)
                if parent_id in shared_parent_ids and parent_id not in seen:
                    shared_parents.append(parent)
                    seen.add(parent_id)
            for index, parent in enumerate(shared_parents, 1):
                sections.append(
                    f'## Shared Parent Algorithm {index} ##\n'
                    f'{algorithm_block(parent, include_guidance=False)}')
            for child_index, (child, group) in enumerate(
                    zip(children, parent_groups), 1):
                sections.append(
                    f'## Child Algorithm {child_index} ##\n'
                    f'{algorithm_block(child, include_guidance=True)}')
                non_shared = [parent for parent in group
                              if cls._parent_identity(parent) not in shared_parent_ids]
                if non_shared:
                    subsection = [
                        f'## Non-shared Parents of Child Algorithm {child_index} ##'
                    ]
                    for parent_index, parent in enumerate(non_shared, 1):
                        subsection.extend((
                            f'# Non-shared Parent {parent_index} #',
                            algorithm_block(parent, include_guidance=False),
                        ))
                    sections.append('\n'.join(subsection))
        return sections, task

    @classmethod
    def get_prompt_reflection(cls, children, parents=None, info=None,
                              parent_info_flag=False, best_worst_flag=False,
                              fitness_flag=0, avg_fitness_flag=False,
                              check_reflection_flag=False, population=None,
                              use_long_term_reflection=True,
                              feedback_method='candidate_comparison',
                              behavior_type=None, behavior_task=None,
                              identical_parent_children_flag=False,
                              shared_parent_children_flag=False,
                              population_comparison=None,
                              comparison_flag=None,
                              attribution_flag=None,
                              summarization_flag=None,
                              attribution_task='good',
                              summarization_task='guidance',
                              insight_flag=None, cause_flag=None,
                              suggestion_flag=None, experience_flag=None,
                              output_fields=None) -> str:
        """Build a reflection prompt for the input ablation study.

        Defaults are the baseline: selected child code only. ``fitness_flag``
        is 0 (code), 1 (code + thought), or 2 (code + thought + score).
        """
        if info is None:
            raise ValueError('info is required for reflection prompts.')
        children = children if isinstance(children, list) else [children]
        parent_groups = parents or [[] for _ in children]
        if len(parent_groups) != len(children):
            raise ValueError('parents must contain one parent group per child.')
        if fitness_flag not in (0, 1, 2):
            raise ValueError('fitness_flag must be 0, 1, or 2.')

        if all(flag is None for flag in (
                comparison_flag, attribution_flag, summarization_flag)):
            if behavior_type is None:
                behavior_type = ('comparison' if feedback_method == 'candidate_comparison'
                                 else 'attribution')
            comparison_enabled = behavior_type == 'comparison'
            attribution_enabled = behavior_type == 'attribution'
            summarization_enabled = behavior_type == 'summarization'
            if attribution_enabled and behavior_task:
                attribution_task = behavior_task
            if summarization_enabled and behavior_task:
                summarization_task = behavior_task
        else:
            comparison_enabled = bool(comparison_flag)
            attribution_enabled = bool(attribution_flag)
            summarization_enabled = bool(summarization_flag)
        if not any((comparison_enabled, attribution_enabled,
                    summarization_enabled)):
            raise ValueError('At least one reflection behavior must be enabled.')
        behavior_task = behavior_task or 'parent_child'
        # Keep behavior_task compatibility while exposing independent flags
        # for the 2x2 sibling-comparison ablation.
        identical_parent_children_flag |= behavior_task == 'children_same_parents'
        shared_parent_children_flag |= behavior_task == 'children_shared_parent'
        sibling_comparison_enabled = (
            comparison_enabled and
            (identical_parent_children_flag or shared_parent_children_flag)
        )
        has_parent = (comparison_enabled and
                      (parent_info_flag or sibling_comparison_enabled) and
                      any(parent_groups))

        def display_score(func):
            score = getattr(func, 'score', None)
            if score is None:
                return None
            # EoH maximizes negative cost internally. Reflection exposes the
            # equivalent positive cost so that lower values are better.
            return -score

        def block(func, include_score=True, include_guidance=False):
            text = ''
            if fitness_flag >= 1:
                thought = str(getattr(func, 'algorithm', '') or '').strip()
                # Records created by older runs may contain a formatting label
                # in the stored thought. Keep the reflection field clean.
                if thought == 'Code:':
                    thought = ''
                text += f'thought: {thought}\n'
            if fitness_flag >= 2 and include_score:
                text += f'score: {display_score(func)}\n'
            if include_guidance and check_reflection_flag:
                guide = getattr(func, '_eoh_generation_suggestion', None)
                if guide:
                    text += f'This algorithm is generated after being guided by {guide}\n'
                experience = (getattr(func, '_eoh_experience', None)
                              if use_long_term_reflection else None)
                if experience:
                    text += f'This path evolved into the algorithm, and the summarized experience is {experience}.\n'
            if hasattr(func, 'to_code_without_docstring'):
                source = func.to_code_without_docstring().rstrip()
            else:
                source = str(func).rstrip()
            text += f'Code:\n```python\n{source}\n```'
            return text

        population_items = list(getattr(population, 'population', population or []))
        population_tasks = {
            'elite_worst': cls._build_elite_worst_input,
            'elite_average': cls._build_elite_average_input,
            'worst_average': cls._build_worst_average_input,
        }
        sections = []
        sibling_sections = None
        if comparison_enabled and sibling_comparison_enabled:
            sibling_sections, detected_task = cls._build_sibling_input(
                children, parent_groups, block,
                allow_identical=identical_parent_children_flag,
                allow_shared=shared_parent_children_flag)
            if sibling_sections:
                sections.extend(sibling_sections)
                behavior_task = detected_task
        if not sibling_sections and has_parent:
            sections.extend(cls._build_parent_child_input(
                children, parent_groups, block))
            behavior_task = 'parent_child'
        elif not sibling_sections:
            sections.append(
                '===== reference =====\n'
                'Here are a few pieces of algorithm to complete the above task.'
            )
            for i, child in enumerate(children, 1):
                sections.append('\n'.join((f'## Algorithm {i} ##',
                                           block(child, include_guidance=True))))
            behavior_task = 'reference'

        if (comparison_enabled and population_comparison is None
                and best_worst_flag):
            population_comparison = 'elite_worst'
        if comparison_enabled and population_comparison is not None:
            if population_comparison not in population_tasks:
                raise ValueError('population_comparison must be elite_worst, '
                                 'elite_average, or worst_average.')
            if not population_items:
                raise ValueError(f'{population_comparison} comparison requires a population.')
            sections.extend(population_tasks[population_comparison](
                population_items, block, display_score))

        if comparison_enabled and avg_fitness_flag and population_items:
            scores = [f.score for f in population_items if f.score is not None]
            if scores:
                average_score = -sum(scores) / len(scores)
                sections.append(
                    f'Population average score: {average_score}'
                )

        processing_blocks = []
        if comparison_enabled:
            processing_blocks.append(cls._processing_block(
                'comparison', behavior_task))
        if attribution_enabled:
            processing_blocks.append(cls._processing_block(
                'attribution', attribution_task))
        if summarization_enabled:
            processing_blocks.append(cls._processing_block(
                'summarization', summarization_task))

        return (f"===== Task Description =====\n{info['task_description']}\n"
                + cls._reflection_input_block(
                    parent_info_flag if comparison_enabled else False,
                    best_worst_flag if comparison_enabled else False,
                    fitness_flag,
                    avg_fitness_flag if comparison_enabled else False) + '\n'
                + '\n'.join(sections) + '\n'
                "===== Processing Instruction =====\n"
                + '\n'.join(processing_blocks) + '\n'
                "Lower scores indicate better algorithms.\n"
                "===== Output Format =====\n"
                + cls._reflection_output_block(
                    output_fields, insight_flag, cause_flag,
                    suggestion_flag, experience_flag) + '\n'
                )

    @classmethod
    def get_prompt_design(cls, info, indivs, suggestion):
        method_name, method_args, func_template, class_args = cls._template_values(info)
        task_prompt = info['task_description']
        for indi in indivs:
            assert hasattr(indi, 'algorithm')
        # create prompt content for all individuals
        indivs_prompt = ''
        for i, indi in enumerate(indivs):
            indi.docstring = ''
            indivs_prompt += f'No. {i + 1} method and the corresponding code are:\n{indi.algorithm}\n{str(indi)}'
        # create prmpt content
        prompt_content = f'''{task_prompt} You need to optimize the method '{method_name}' in it.
I have {len(indivs)} implementations of this method with their codes as follows:
{indivs_prompt}
{class_args}
{method_args}
This is the format for your reply:
{func_template}
Here is a suggestion to guide the design of a new algorithm:
{suggestion}
{cls.requirements()}
Do not give additional explanations.'''
        return prompt_content

    @classmethod
    def get_prompt_experience(cls, info, references):
        """Build the long-term reflection prompt from reference histories."""
        paths = []
        for ref in references:
            suggestion = getattr(ref, '_eoh_generation_suggestion', None)
            experience = getattr(ref, '_eoh_experience', None)
            if suggestion or experience:
                paths.append((suggestion, experience))
        if not paths:
            return None
        sections = []
        for index, (suggestion, experience) in enumerate(paths, 1):
            label = ('## Evolution path ##' if len(paths) == 1
                     else f'## Evolution path {index} ##')
            lines = [label]
            if experience:
                lines.append(
                    'The experience gained from evolving algorithms along this path '
                    f'is {experience}.'
                )
            if suggestion:
                lines.append(
                    'The most recent design algorithm guidance for this evolution path '
                    f'is {suggestion}.'
                )
            sections.append('\n'.join(lines))
        return (f"Task Description: {info['task_description']}\n"
                + '\n'.join(sections) + '\n\n'
                'Based on the above, sum up some experiences that align with evolutionary trends.')

    @staticmethod
    def append_reflection(prompt: str, suggestion: str | None, requirements: str) -> str:
        if not suggestion:
            return prompt
        return f'''{prompt}
Use the following reflection as guidance for this generation:
{suggestion}
{requirements}'''

    @classmethod
    def create_instruct_prompt(cls, prompt: str) -> List[Dict]:
        content = [
            {'role': 'system', 'message': cls.get_system_prompt()},
            {'role': 'user', 'message': prompt}
        ]
        return content

    @classmethod
    def get_system_prompt(cls) -> str:
        return ''
    
    @staticmethod
    def requirements() -> str:
        return """Requirements:
    1.Use a sentence inside the {} after 'thought:' to describe your algorithm.
    2.Implement the method after 'Code:'.
    3.If you use any python library or module such as numpy, import it inside the method body before first use. Do not assume imports outside this method exist.
    4.Do not rely on hidden global variables, hidden class fields, or methods that are not visible in the prompt outside the standard python library."""

    # Keep compatibility with the existing m2 prompt text.
    _requirements = requirements

    @staticmethod
    def _template_values(info: dict):
        """Build every prompt field from task metadata."""
        required = ('method_name', 'func_template', 'method_signature')
        missing = [key for key in required if key not in info]
        if missing:
            raise ValueError(f'info is missing required fields: {", ".join(missing)}.')
        reply_template = (info['func_template']
                          .replace('<method_name>', info['method_name'])
                          .replace('<method_args>', info['method_signature']))
        class_args = info.get('class_args', '').strip()
        method_args = info.get('method_args', '').strip()
        class_section = (f'This is the information about the variables in this class:\n{class_args}'
                         if class_args else '')
        method_section = (f'These are the relevant parameters for this method:\n{method_args}'
                          if method_args else '')
        return info['method_name'], f'{method_section}', reply_template, f'{class_section}'
    
    @classmethod
    def get_prompt_i1(cls, info: dict | None = None):
        method_name, method_args, func_template, class_args = cls._template_values(info)
        task_prompt = info['task_description']
        prompt_content = f'''{task_prompt} You need to optimize the method '{method_name}' in it.
{class_args}
{method_args}
This is the format for your reply:
{func_template}
{cls.requirements()}
Do not give additional explanations.'''
        return prompt_content

    @classmethod
    def get_prompt_e1(cls, indivs: List[Function], info: dict | None = None, suggestion: str | None = None):
        method_name, method_args, func_template, class_args = cls._template_values(info)
        task_prompt = info['task_description']
        for indi in indivs:
            assert hasattr(indi, 'algorithm')
        # create prompt content for all individuals
        indivs_prompt = ''
        for i, indi in enumerate(indivs):
            indi.docstring = ''
            indivs_prompt += f'No. {i + 1} method and the corresponding code are:\n{indi.algorithm}\n{str(indi)}'
        # create prmpt content
        prompt_content = f'''{task_prompt} You need to optimize the method '{method_name}' in it.
I have {len(indivs)} implementations of this method with their codes as follows:
{indivs_prompt}
{class_args}
{method_args}
This is the format for your reply:
{func_template}
These are some suggestions after reflecting on the given algorithms:
{suggestion}
Please refer to the given suggestions and help me create a new algorithm that has a totally different form from the given ones. 
{cls.requirements()}
Do not give additional explanations.'''
        return prompt_content

    @classmethod
    def get_prompt_e2(cls, indivs: List[Function], info: dict | None = None,
                      suggestion: str | None = None):
        method_name, method_args, func_template, class_args = cls._template_values(info)
        task_prompt = info['task_description']
        for indi in indivs:
            assert hasattr(indi, 'algorithm')

        # create prompt content for all individuals
        indivs_prompt = ''
        for i, indi in enumerate(indivs):
            indi.docstring = ''
            indivs_prompt += f'No. {i + 1} method and the corresponding code are:\n{indi.algorithm}\n{str(indi)}'
        # create prmpt content
        prompt_content = f'''{task_prompt} You need to optimize the method '{method_name}' in it.
I have {len(indivs)} implementations of this method with their codes as follows:
{indivs_prompt}
{class_args}
{method_args}
This is the format for your reply:
{func_template}
These are some suggestions after reflecting on the given algorithms:
{suggestion}
Please refer to the given suggestions and identify the common backbone idea in the provided methods and help me create a new algorithm that has a totally different form from the given ones but can be motivated from them.
{cls.requirements()}
Do not give additional explanations.'''
        return prompt_content

    @classmethod
    def get_prompt_m1(cls, indi: Function, info: dict | None = None,
                      suggestion: str | None = None):
        method_name, method_args, func_template, class_args = cls._template_values(info)
        task_prompt = info['task_description']
        assert hasattr(indi, 'algorithm')
        indiv_prompt = f'{indi.algorithm}\n{str(indi)}'

        # create prmpt content
        prompt_content = f'''{task_prompt} You need to optimize the method '{method_name}' in it.
I have a implementation of this method with its code as follows:
{indiv_prompt}
{class_args}
{method_args}
This is the format for your reply:
{func_template}
These are some suggestions after reflecting on the given algorithms:
{suggestion}
Please refer to the given suggestions and assist me in creating a new algorithm that has a different form but can be a modified version of the algorithm provided.
{cls.requirements()}
Do not give additional explanations.'''
        return prompt_content

    @classmethod
    def get_prompt_m2(cls, indi: Function, info: dict | None = None,
                      suggestion: str | None = None):
        method_name, method_args, func_template, class_args = cls._template_values(info)
        task_prompt = info['task_description']
        assert hasattr(indi, 'algorithm')
        indiv_prompt = f'{indi.algorithm}\n{str(indi)}'
        # create prmpt content
        prompt_content = f'''{task_prompt} You need to optimize the method '{method_name}' in it.
I have a implementation of this method with its code as follows:
{indiv_prompt}
{class_args}
{method_args}
This is the format for your reply:
{func_template}
These are some suggestions after reflecting on the given algorithms:
{suggestion}
Please refer to the given suggestions and identify the main algorithm parameters and assist me in creating a new algorithm that has a different parameter settings of the score function provided.
{cls._requirements()}
Do not give additional explanations.'''
        return prompt_content
